FROM node:20-alpine

# prisma thing
RUN apk add --no-cache openssl

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate
RUN npx prisma migrate dev --name init

CMD ["npm", "run", "dev"]

