FROM node:20-alpine

# prisma thing
RUN apk add --no-cache openssl

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
COPY prisma ./prisma       

RUN npx prisma generate

CMD ["npm", "run", "dev"]

